### ISSUE TITLE
Ask for code

### ISSUE THREAD

**Issue by chouqin3** [xychen2022/3DFasterRCNN#1]
Sorry to disturb you. I submit a paper regarding landmark localization on medical images, one of the reviewers asked me to compare ours with your method. Could you send me the whole code to my email (lugang@seu.edu.cn). I have to contact you in this way since I can't find your email in your paper. I'm looking forward to your reply, thanks.

**Comment by xychen2022** [comment]
The code has been sent. Thanks for your interest in our work!

**Comment by chouqin3** [comment]
Thanks for your great work.
